version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: helloworld
      MYSQL_ROOT_PASSWORD: root1root
    volumes: 
      - ./src/main/resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3311:3306
      
  app:
     build:
       context: .
     ports:
        - 8080:8080
     restart: always
     environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restaurantdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
       DATABASE_USER: myapp-user
       DATABASE_PASSWORD: helloworld
     depends_on:
        - database
        