version: "3.8"

services:
  database:
    image: mysql:8.0.20
    volumes: 
      - ./src/main/resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3311:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1root
      MYSQL_DATABASE: restaurantdb
      
