version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root1root
      MYSQL_ROOT_PASSWORD: root1root
    volumes: 
      - ./src/main/resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#    ports:
#      - 3311:3306
      
  app:
     build:
       context: .  
     ports:
        - 8080:8080
     restart: always
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/restaurantdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
     depends_on:
        - database