-- MySQL Script generated by MySQL Workbench
-- Mon Feb 10 00:03:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurantdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurantdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurantdb` ;

-- -----------------------------------------------------
-- Table `restaurantdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantdb`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `funds` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` LONGTEXT NULL DEFAULT NULL,
  `registration_date` DATETIME NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `surname` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKr43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantdb`.`menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantdb`.`menu_items` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `nameua` VARCHAR(255) NULL DEFAULT NULL,
  `price` BIGINT(20) NOT NULL,
  `storage_quantity` BIGINT(20) NOT NULL,
  `weight` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK8y3q2e0rhd7t8o0fg246wb2i2` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantdb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantdb`.`orders` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `order_statement` VARCHAR(255) NULL DEFAULT NULL,
  `quantity` BIGINT(20) NOT NULL,
  `time` TIME NULL DEFAULT NULL,
  `total_price` BIGINT(20) NOT NULL,
  `menu_item_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKs7nmoqxgelq8fth8eanqnagev` (`menu_item_id` ASC) VISIBLE,
  INDEX `FK32ql8ubntj5uh44ph9659tiih` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK32ql8ubntj5uh44ph9659tiih`
    FOREIGN KEY (`user_id`)
    REFERENCES `restaurantdb`.`users` (`id`),
  CONSTRAINT `FKs7nmoqxgelq8fth8eanqnagev`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `restaurantdb`.`menu_items` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantdb`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantdb`.`bills` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `invoice_date_time` DATETIME NULL DEFAULT NULL,
  `payment_date_time` DATETIME NULL DEFAULT NULL,
  `statement` VARCHAR(255) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK2s1iwv6bgsmh8u9awhdd1aela` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FK2s1iwv6bgsmh8u9awhdd1aela`
    FOREIGN KEY (`order_id`)
    REFERENCES `restaurantdb`.`orders` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
